log:
  disable_sentry: true
  level: info

db:
  url: postgres://postgres:postgres@localhost:5432/blobs?sslmode=disable

listener:
  addr: :8000

client:
  endpoint: http://localhost:80

submit:
  endpoint: http://localhost:80

keys:
  source: GBA4EX43M25UPV4WIE6RRMQOFTWXZZRIPFAI5VPY6Z2ZVVXVWZ6NEOOB
  signer: SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4

cop:
  disabled: true